### ISSUE TITLE
IRR explorer front end crashes on large AS-SETs

### ISSUE THREAD

**Issue by teunvink** [NLNOG/irrexplorer#262] opened 2023-07-04 19:48 UTC
IRR explorer seems to have problems expanding large AS-sets. One we observed which seems to cause issues on multiple instances is `AS-ALSARD-SET`. The IRR explorer webpage is unresponsive as a result of opening that AS-SET.

**Comment by nbakker** [comment] 2023-07-04 23:09
Possibly related to irrd timing out and closing the TCP connection with irrexplorer not handling that gracefully.

**Comment by mxsasha** [comment] 2024-09-30 09:38
Duplicate of #193

**Closed by mxsasha** 2024-09-30 09:38 UTC
Labels: bug
