### ISSUE TITLE
Using AltDB or RADB results in a warning?

### ISSUE THREAD

**Issue by thegushi** [NLNOG/irrexplorer#153] opened 2022-03-24 01:49 UTC
For my own AS (as393507) I used to get the "everything looks good" despite the fact that I was using a third party Routing Registry.

Is there some reason that this is now given a warning like "Expected route object in ARIN, but only found in other IRRs"

Other RIR's like RADB are often easier to update for large complicated networks for those of us who don't love email templates, and in some cases, like my day job, where we have resources from multipile RIR's, it's the only way forward.

(Now, I'm not sure why my v6 block shows in the ARIN registry but my V4's don't)

**Comment by forkwhilefork** [comment] 2022-03-24 09:23
ARIN and RIPE both have APIs, and before that I knew people who automated the emails. RADB is not the only option, nor is it a generally recommend one. ALTDB does a better job cleaning up stale data but it's still non-authoritative. A little bit of automation easily solves the issue of fragmentation for large networks, which for a large company like you describe is easily within reach.

Using the authoritative IRR databases is the correct solution, and it's reasonable to call that out in irrexplorer.

**Comment by thegushi** [comment] 2022-03-29 22:23
Also, it seems ARIN *does* now have a web UI, which is useful.

I will point out one other edge case here: At least some of the resources I announce are legacy resources, registered before the existence of ARIN (we're old).  As far as I know, there's no WHOIS/IRR way to detect these, but those are the case for two of the netblocks I posted.  (If there were an easy way of detecting these, that would be a useful thing for the code to point out).

Putting those under an ARIN RSA/LRSA would make these two (hobbyist) IP blocks go from being $0 a year, to being many hundreds of dollars a year.  But without doing that, using IRR with ARIN, or using RPKI are not an option.

Also, can you point me at some kind of document as to what the "best accepted practices" are?  I know a year ago, my irrexplorer was all green, and now it isn't.  Like using SSLLabs, it's a moving target and it would be nice to be able to know what I *should* be doing rather than guessing.

**Comment by forkwhilefork** [comment] 2022-03-29 22:43
Your point about legacy resources is valid; it would be good if irrexplorer differentiated those prefixes and applied different guidelines. LRSAs are not appropriate for everyone.

As far as I know, there's no single source of truth for this stuff. Most of my knowledge and opinions come from watching/reading talks, as well as the writings of people like Job.

I will also note, though, that irrexplorer is not the internet police. No one will come knocking at your door if it's not all green. So, if irrexplorer is a little wrong, it won't directly cause you a problem.

**Comment by thegushi** [comment] 2022-04-02 08:08
Roger.  If this behavior is by design, feel free to resolve this.  I can't find a programmatic way to detect legacy resources, sadly.  I'll be opening a new issue in a minute for something else that arguably is a bug.

**Comment by mustangthz** [comment] 2022-04-13 21:11
> ARIN and RIPE both have APIs, and before ARIN had one I knew people who automated the emails. RADB is not the only option, nor is it a generally recommend one. ALTDB does a better job cleaning up stale data but it's still non-authoritative. A little bit of automation easily solves the issue of fragmentation for large networks, which for a large company like you describe is easily within reach.
> 
> Using the authoritative IRR databases is the correct solution, and it's reasonable to call that out in irrexplorer.

Let's be 100% clear.  People use non-authoritative databases for many reasons.  You do not get to dictate what IRR we chose to use as a company.  If you want to re-add support the use of them, that'd be great.  If not, we're going to deprecate the use of IRRexplorer.

**Comment by job** [comment] 2022-04-13 21:22
ALTDB & RADB are 100% supported in irrexplorer. No plans to change that!

The goal of this project is to encourage people towards abiding to best-current-practices while navigating a complicated set of information sources.

For some people a warning "hey, you are using a third party IRR - you might be missing out on included-in-price IRR services in a more authoritative place!" is useful, for other people its "yup, I know what I'm doing". The goal of irrexplorer is to increase visibility for operators, not to dictate anything.

**Comment by forkwhilefork** [comment] 2022-04-13 21:28
> Let's be 100% clear. People use non-authoritative databases for many reasons. You do not get to dictate what IRR we chose to use as a company. If you want to re-add support the use of them, that'd be great. If not, we're going to deprecate the use of IRRexplorer.

I'm not dictating anything. I don't maintain irrexplorer, but even if I did, like I said before, IRRexplorer is not the internet police.

You are, obviously, free to do whatever you want. I was just poking some holes in OP's initial argument.

Also - as far as I'm aware, IRRexplorer is a free service provided to the internet community for convenience. I'm speaking only for myself here, but I don't expect they particularly care if you deprecate your use of them.

**Comment by thegushi** [comment] 2022-04-13 21:43
Suspect this was related to the DB cleanup done as a result of the “stuck” resources I mentioned in the other ticket.

-Dan

**Comment by job** [comment] 2022-04-13 21:45
@mustangthz Can you share which AS-SET primary key in which database were you expecting to see?

**Comment by mustangthz** [comment] 2022-04-13 21:57
AS-CORESITE 

Expect to see our AS as well as a child AS-SET with our customers ASs

Chris

**Comment by job** [comment] 2022-04-13 22:02
Weird, must be a caching bug of sorts. Manually I see the following, which is what I'd also expect in irrexplorer. There may be a transcient issue with irrexplorer itself.

```
feather$ whois -h whois.radb.net AS-CORESITE
as-set:     AS-CORESITE
descr:      Coresite AS-SET
members:    AS2734,
            AS-CORESITE-CUSTOMERS,
            AS32743
admin-c:    REEDC55-ARIN
tech-c:     REEDC55-ARIN
notify:     netops@coresite.com
mnt-by:     MAINT-AS32743-RADB
changed:    chris.reed@coresite.com 20200901  #00:04:30Z
source:     RADB
```

@teunvink

**Comment by teunvink** [comment] 2022-04-13 22:11
I think this is totally unrelated to this original issue. I see similar issues for as-sets in other databases, https://irrexplorer.nlnog.net/as-set/AS-BIT (which is in RIPE) for example. And I see similar things in my local setup. 

To be clear, as Job stated nothing changed in how irrexplorer handles data in other databases like RADB and AltDB.

**Comment by teunvink** [comment] 2022-04-14 20:01
> Seeing the same thing for AS1280 (as an example) where almost nothing is shown from RADB.  Everything there now shows “no route objects match dfz origin”.  I think the cleanup Teun mentioned they did in [#148](https://github.com/NLNOG/irrexplorer/issues/148) are the cause.

That seems to be the trigger, but it should be the cause of these problems. AS-sets from various sources seem to be missing in `irrd`. I'm not sure yet why.

> I know this git repo is for the actual code base — is there a different place to raise questions related to irrexplorer.nlnog.net <http://irrexplorer.nlnog.net/> (i.e. site problems vs code problems?).  There’s a distinct lack of contact info there.

You can ask them here, at least for now, since there's no way to configure a contact in the web front end. I added a `site` label yesterday to handle this and will open an issue to add a feature to configure the hoster's contact details.

**Comment by thegushi** [comment] 2022-04-16 23:13
So we've seen as-sets get "stuck" in the system, and also, polling fail to add them.  IDK what the DB backend is, but is there a corrupt/crashed table somehow?

(A week later, AS1280 is still missing nearly all its RADB entries, and there are lots in RADB proper).

-Dan

**Comment by teunvink** [comment] 2022-04-18 18:53
We're still looking into this, but this is a project managed by a few volunteers and time is limited, so unfortunately this takes a bit longer than we'd like. 

I see similar issues on other IRRexplorer instances as well, it seems to be that some AS-SETs are missing in the `irrd` backend (which isn't part of the IRRexplorer toolset). We don't see any yet indications on why some (but not all) AS-SETs are missing.

**Comment by teunvink** [comment] 2022-04-20 12:19
A forced refresh of the entire database has been triggered, this should be resolved soon.

**Comment by teunvink** [comment] 2022-04-23 12:07
This import was completed three days ago, I'm closing this issue now. Feel free to open a new issue if you experience any new issues.

**Closed by teunvink** 2022-04-23 12:07 UTC
Labels: site
